language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always

env:
  global:
   - secure: "d72scMGybGfXPuGKwvFXOF+3fq9d/FV5CDN1uAD5GW1r+vV0dZkKnoG3ZZ7bwikOIei4Z5zQ1oVhnPhHOS2ReCxmui1uwcGJnwl1Pwpmq/zei2sNsqyPMGA3q0v87g8wr5G+l3cRPDMBlqtjjuYHfbvyXPbYf0qTJ9NDWybg40s="

addons:
  coverity_scan:
    project:
      name: "maxmind/geoip-api-java"
      description: "Build submitted via Travis CI"
    notification_email: dev@maxmind.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: .*coverity.*
